### ISSUE TITLE
systax error in line 567, mysmb.py

### ISSUE THREAD

**Issue by nullbaka** [3ndG4me/AutoBlue-MS17-010#18]
am learning to exploit without metasploit. I came across autoblue when attempting to do so in HTB-blue.

When I do  `python eternal_checker.py` i get errors

Line 427 in mysmb.py:
> except Exception as e:

Line 567 in mysmb.py
> except Exception, e:

I am stuck at how to best use it, py2 or py3. i tried using py2 and 
1. eternal_checker.py ran but it didn't list out named pipes
2. didn't get active session in `msf5` after `python eternalblue_exploit7.py [IP:XX:XX:XX] shellcode/sc_all.bin`

Help please

**Comment by 3ndG4me** [comment]
For your first question, that issue is now resolved by PR #17 

For your second, this exploit code was originally written for python2, but regardless most of it could be compatible with either version (if it runs then it runs). That said I will look into python2 versus python3 compatibility in the near future just in case there's more issues that exists similar to the mysmb.py issue.

Otherwise if you're not getting shells/the checker isn't returning vulnerability info, consider that the target may not be vulnerable 😄
