### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by TonyStarkn** [3ndG4me/AutoBlue-MS17-010#51]
After doin every steps perfectly, i come up with this error "No route to host". What is the solution for this??
![image](https://github.com/3ndG4me/AutoBlue-MS17-010/assets/169923678/3802b4e0-7f8a-4de4-b6b2-472500cc8372)
This is whats spws up!!

**Comment by 3ndG4me** [comment]
I appreciate the screenshot that helps some, but I have already stated some trouble shooting steps in your last issue. I don't mean to come off as rude or unhelpful, but I cannot provide help without an actual problem to solve.

This looks like a networking issue, not a tool issue. Have you tried other tools to confirm you can reach your target or that the service is even online. Do you have a way to check if EDR is potentially blocking the request? Also that particular variant requires named pipes to be available, are there any? 

Make sure you know which exploit to use and what it does before you just run scripts from the internet 😉. Try running the eternal checker script and seeing what it shows?

Again I'm going to close and lock this issue. I apologize if you have done all these steps already but I suggest you do the following and bring evidence for each before opening another issue otherwise I will not be able to even begin to help.

1. Ping the host. Does it respond to a ping?
2. Run an nmap scan against port 445, does the port show as open?
3. Run the eternal checker script, is the target vulnerable and are there any named pipes open?
4. Run the metasploit scanner module, does it return that the target is vulnerable?
5. If all of those things return without any issues, then you should open an issue on this repo that showcases all the steps you tried, plus the error you get when running zzz. If the checker script doesn't have named pipes but shows as unpatched then try using the normal exploit. 

_But in either case do not open another issue without trying those steps first. _

Sincerely don't mean to sound rude, my sentiment is that I am unable to help you with this little amount of information and I want to help by giving you feedback on how to troubleshoot and properly open an issue. This error is a very generic one and if you know why it occurs usually then you'd know to check these other factors first before assuming it is the tool.

It could be the tool, but seeing as I used it just last week in this same scenario, I'm more inclined to think there's a separate issue at play. Please try that list of things, and good luck!
